apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alertmanager
  name: alertmanager
  namespace: secu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alertmanager
    spec:
      containers:
      - image: ${IMAGE}:${VERSION}
        name: alertmanager
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: secu
spec:
  selector:
    app: alertmanager
  ports:
    - port: 8080
