apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zosecu
    tier: frontend
  name: zosecu-front
  namespace: secu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zosecu
      tier: frontend
  template:
    metadata:
      labels:
        app: zosecu
        tier: frontend
    spec:
      containers:
        - image: ${IMAGE}:${VERSION}
          name: front
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: secu
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: zosecu
    tier: frontend
