apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-serviceaccount
  namespace: secu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: zo-secu-webhook-clusterrole
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zo-secu-webhook-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zo-secu-webhook-clusterrole
subjects:
  - kind: ServiceAccount
    name: webhook-serviceaccount
    namespace: secu
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: webhook-config
  namespace: secu
data:
  config.yaml: |-
    userInfoEndpoint: "http://projectmanager:8080"
    scanner:
      type: zerooneScanner
      zerooneScanner:
        namespace: secu
        scannerImage: zerooneai/scanner:t0.0.4
        resultSenderImage: zerooneai/resultsender:dependencytrack-0.0.3
        dependencyTrackEndpoint: "http://dependency-track-apiserver.dependency-track.svc.cluster.local:80"
        dependencyTrackApiKey: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: secu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      serviceAccountName: webhook-serviceaccount
      containers:
        - image: ${IMAGE}:${VERSION}
          name: webhook
          args: ["-config=/.webhook/config/config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /.webhook/config/
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      volumes:
        - name: config
          configMap:
            name: webhook-config
---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: secu
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webhook
